name: Lint with dprint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update rustup
        run: rustup self update

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable -c rustfmt
          rustup default stable

      - uses: dprint/check@v2.2